### ISSUE TITLE
An issue about runnig the test code with node.js

### ISSUE THREAD

**Issue by yongjin-shin** [myphysicslab/myphysicslab#3]
Hi Erik,

I do appreciate you sharing your wonderful work.
Since I am not familiar with javascript, I have been trying to debug your code with using node.js
However, I cannot solve one error. It seems that this error comes from 'closure library' not from your code, but
I am just wondering if you have any idea to solve it.

The following code is the first two lines in SingleTest.js with calling ```require``` function for node.js

```
require("google-closure-library");
goog.module('myphysicslab.test.SingleTest');
const CircleCircleTest = goog.require('myphysicslab.test.CircleCircleTest');
```

And the debugger shows:

```
Waiting for the debugger to disconnect...
/Users/yongjinshin/node_modules/google-closure-library/closure/goog/base.js:448
    throw new Error(
    ^

Error: Module myphysicslab.test.SpeedTest has been loaded incorrectly. Note, modules cannot be loaded as normal scripts. They require some kind of pre-processing step. You're likely trying to load a module via a script tag or as a part of a concatenated bundle without rewriting the module. For more info see: https://github.com/google/closure-library/wiki/goog.module:-an-ES6-module-like-alternative-to-goog.provide.
    at Object.goog.module (/Users/yongjinshin/node_modules/google-closure-library/closure/goog/base.js:448:11)
    at Object.<anonymous> (/Users/yongjinshin/Desktop/js_test/myphysicslab/src/test/SpeedTest.js:15:6)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Thanks, again
YJ

**Comment by myphysicslab** [comment]
Hello YJ,
Thanks for your comments.  myPhysicsLab is not designed to be run from
source code, it must first be compiled with the Google closure compiler
tool.  I've never used node.js so I can't speak to how to use node.js with
myPhysicsLab, but I doubt it would work without a lot of effort.  Have you
seen this page?
https://www.myphysicslab.com/develop/docs/Building.html

Best regards,
--ErikN

**Comment by yongjin-shin** [comment]
Indeed, I have seen your document. 
Actually I need change some settings in your models (i.e. positions of balls) for my research experiments.
As my code for experiments is written in python, I have been trying to use your simulators without using a browser.
Anyway, I will figure it out! Thank you for your kind help, though.

With Regards,
YJ

**Comment by myphysicslab** [comment]
Which simulation do you want to change?  Some things can be done without
recompile.
