### ISSUE TITLE
myphysicslab website is not working

### ISSUE THREAD

**Issue by IceServal** [myphysicslab/myphysicslab#4]
I known myphysicslab in "Ten Minites Physics" lesson 05 and then I try to visit "www.myphysicslab.com/pendulum/pendulum-en.html" it recommended, but I failed to connect to it and get errno: `ERR_CONNECTION_TIMED_OUT`, even with my proxy I got same errno.

Also the homepage "www.myphysicslab.com" is not working, is there any thing I can do to read the contents of the website?

**Comment by myphysicslab** [comment]
It seems to all be working for me.  Do these links below work for you? 

https://www.myphysicslab.com/pendulum/pendulum-en.html 
https://www.myphysicslab.com

www.myphysicslab.com/pendulum/pendulum-en.html 
www.myphysicslab.com

I did a major rewrite of the source code from JavaScript to TypeScript in the last week, so it's possible there is a problem somehow, but I'm not seeing any problem.

**Comment by IceServal** [comment]
No, still can not. I tried to visit websites above with wired network, wifi, mobile network. All these tries are failed. But I can ping to your website, no package loss, TTL is 63 and responsing time less than 1ms.
![image](https://github.com/myphysicslab/myphysicslab/assets/10845667/5268b7fc-e4b7-409b-a1e7-a7cbde0c6a66)

I'm wondering whether I'm blocked by your firewall. I'm trying to visit your website in chinese mainland. Can that be the reason I can not visit your websites?

**Comment by IceServal** [comment]
ooooooooh, it's okay, that's the reason, I change my system proxy mode and visit your websites successfully!
